@HOST = http://localhost:3333
@IDJOB = 0a4f1d8d-0e26-41c8-8226-9f1dab46040a

GET {{HOST}}/job/{{IDJOB}}/candidate HTTP/1.1
Content-Type: application/json 
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2ZmFkNmQ2LWZhOWItNGU4ZC05YjMzLTQwODJjYTU2ODczMSIsIm5hbWUiOiJEYXBobmUiLCJlbWFpbCI6ImRhcGhuZUBkb2cuY29tIiwidHlwZSI6IlIiLCJlbnRlcnByaXNlTmFtZSI6Ikdyb3dkZXYgcGFyYSBQZXRzIiwiaWF0IjoxNjkxNjI5MDg3fQ.lLnYSJsgtOu0EoGEZCQYfdocJ84_qiwVAelpjm5FgEQ