@HOST = http://localhost:8080 

GET {{HOST}}/recruiter HTTP/1.1
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhYmNkNDZkLTFjMzEtNGZhNy1hNWZmLTNiNThhZjYxZGM5YiIsIm5hbWUiOiJKb8OjbyBQZWRybyIsImVtYWlsIjoiam9hb0BnbWFpbC5jb20iLCJ0eXBlIjoiUiIsImVudGVycHJpc2VOYW1lIjoiR3Jvd2RldiBTQSIsImlhdCI6MTY5MDkzMTU4NH0.aoge1wniTNcyFT1xkrWnYtU79_yUfkoI_gKZGyFymbQ