@HOST = http://localhost:3333

GET {{HOST}}/application/job HTTP/1.1
Content-Type: application/json 
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlNGIwZjNjLTgwOGEtNDk5My04ZjFmLWE0NTdhOThiMWY2MiIsIm5hbWUiOiJKdWxpYW5hIiwiZW1haWwiOiJqdWxpYW5hQGdyb3dkZXYuY29tIiwidHlwZSI6IkMiLCJlbnRlcnByaXNlTmFtZSI6bnVsbCwiaWF0IjoxNjkxNjMwMTAwfQ.vxUOZZ8pz9GYwLTqj7w-5dGupQ7DvAZqzeAL3Eym-1M